name: movinfo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  http: ^1.2.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/release_date.png
    - assets/icons/popularity.png
    - assets/Illustrations/film.png
    - assets/icons/Rate.svg
    - assets/icons/date.svg
    - assets/icons/like.svg
    - assets/icons/home.svg
    - assets/icons/search.svg
    - assets/icons/bookmark.svg
    - assets/icons/user.svg
  fonts:
    - family: Abrill
      fonts:
        - asset: assets/fonts/Abril_Fatface/AbrilFatface-Regular.ttf
        
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial/Questrial-Regular.ttf